In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
var = np.arange(20).reshape(5,4)

In [5]:
var.sum()

190

In [6]:
var.sum(axis = 0)

array([40, 45, 50, 55])